// Mocks generated by Mockito 5.0.15 from annotations
// in payflow/test/modules/splash/splash_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:payflow/shared/auth/auth_controller.dart' as _i2;
import 'package:payflow/shared/models/user_model.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i2.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setUser(_i3.BuildContext? context, _i4.UserModel? user) =>
      super.noSuchMethod(Invocation.method(#setUser, [context, user]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<void> saveUser(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#saveUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> currentUser(_i3.BuildContext? context) =>
      (super.noSuchMethod(Invocation.method(#currentUser, [context]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  String toString() => super.toString();
}
